POST http://localhost:3001/api/register
content-type: application/json

{
    "user_email": "huyson202@gmail.com",
    "user_password": "huyson201",
    "user_name": "asdqwedsa"
   
}

###
POST http://localhost:3001/api/login
content-type: application/json 

{
    "user_email" :"huyson@gmail.com",
    "user_password": "asdasd123"
}

###
POST http://localhost:3001/api/refresh-token
content-type: application/json 

{
    "refreshToken" :"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiI1NzllOTU5NS04MzQ3LTRlNWYtODE1MC05MTQzMTI1Nzk3ZWUiLCJ1c2VyX25hbWUiOiJhc2Rxd2Vkc2EiLCJ1c2VyX2VtYWlsIjoiaHV5c29uQGdtYWlsLmNvbSIsInVzZXJfaW1hZ2UiOm51bGwsInVzZXJfcm9sZSI6InVzZXIiLCJjcmVhdGVkQXQiOiIyMDIxLTEwLTA0VDEyOjI3OjQyLjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIxLTEwLTA0VDEyOjQyOjI0LjAwMFoiLCJpYXQiOjE2MzMzNTE2MjAsImV4cCI6MTYzMzM1MTY1MH0.Jj7XfIgsWlXJS81e32vRCvp4r7bHH63Ji4trfJyHeOo"
}